// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqpCp-QmuL1IfjP604hC8sSmeErHa94jc',
    appId: '1:877864462232:web:00c17d79fe6794e0ad2ded',
    messagingSenderId: '877864462232',
    projectId: 'app-project-2147',
    authDomain: 'app-project-2147.firebaseapp.com',
    storageBucket: 'app-project-2147.firebasestorage.app',
    measurementId: 'G-4GL8MJ44LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAncU2sZzTv2imDc5oe1QQUZ4EQNQkZk',
    appId: '1:877864462232:android:fbfbe7cf587c1435ad2ded',
    messagingSenderId: '877864462232',
    projectId: 'app-project-2147',
    storageBucket: 'app-project-2147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfBjWDkSVM8Wuwu_eYU4crI8Fr0_rub0',
    appId: '1:877864462232:ios:d236e0a677e9eec1ad2ded',
    messagingSenderId: '877864462232',
    projectId: 'app-project-2147',
    storageBucket: 'app-project-2147.firebasestorage.app',
    iosClientId: '877864462232-93sv1408aaqdc0njvi011bee524vha7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlfBjWDkSVM8Wuwu_eYU4crI8Fr0_rub0',
    appId: '1:877864462232:ios:d236e0a677e9eec1ad2ded',
    messagingSenderId: '877864462232',
    projectId: 'app-project-2147',
    storageBucket: 'app-project-2147.firebasestorage.app',
    iosClientId: '877864462232-93sv1408aaqdc0njvi011bee524vha7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqpCp-QmuL1IfjP604hC8sSmeErHa94jc',
    appId: '1:877864462232:web:2b0b5312ea7303fbad2ded',
    messagingSenderId: '877864462232',
    projectId: 'app-project-2147',
    authDomain: 'app-project-2147.firebaseapp.com',
    storageBucket: 'app-project-2147.firebasestorage.app',
    measurementId: 'G-WXMQJ9R27X',
  );
}
